# Generated by Django 3.0.4 on 2020-03-24 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ts_code', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=6)),
                ('name', models.CharField(max_length=36)),
                ('area', models.CharField(blank=True, max_length=36, null=True)),
                ('industry', models.CharField(blank=True, max_length=36, null=True)),
                ('fullname', models.CharField(blank=True, max_length=256, null=True)),
                ('enname', models.CharField(blank=True, max_length=256, null=True)),
                ('market', models.CharField(blank=True, max_length=18, null=True)),
                ('exchange', models.CharField(blank=True, max_length=18, null=True)),
                ('curr_type', models.CharField(blank=True, max_length=18, null=True)),
                ('list_status', models.CharField(blank=True, max_length=1, null=True)),
                ('list_date', models.DateField(blank=True, max_length=8, null=True)),
                ('delist_date', models.DateField(blank=True, max_length=8, null=True)),
                ('is_hs', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.Stock')),
                ('exchange', models.CharField(blank=True, max_length=18, null=True)),
                ('chairman', models.CharField(blank=True, max_length=36, null=True)),
                ('manager', models.CharField(blank=True, max_length=36, null=True)),
                ('secretary', models.CharField(blank=True, max_length=36, null=True)),
                ('reg_capital', models.FloatField()),
                ('setup_date', models.DateField(blank=True, max_length=8, null=True)),
                ('province', models.CharField(blank=True, max_length=36, null=True)),
                ('city', models.CharField(blank=True, max_length=36, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('office', models.CharField(blank=True, max_length=256, null=True)),
                ('employees', models.IntegerField(blank=True, null=True)),
                ('main_business', models.TextField(blank=True, null=True)),
                ('business_scope', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('start_date', models.DateField(blank=True, max_length=8, null=True)),
                ('end_date', models.DateField(blank=True, max_length=8, null=True)),
                ('ann_date', models.DateField(blank=True, max_length=8, null=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='HsConst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_type', models.CharField(max_length=2)),
                ('in_date', models.DateField(blank=True, null=True)),
                ('out_date', models.DateField(blank=True, null=True)),
                ('is_new', models.BooleanField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock')),
            ],
        ),
    ]
