# Generated by Django 3.0.4 on 2020-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.TextField(max_length=9)),
                ('symbol', models.TextField(max_length=6)),
                ('name', models.TextField(max_length=36)),
                ('area', models.TextField(blank=True, max_length=36, null=True)),
                ('industry', models.TextField(blank=True, max_length=36, null=True)),
                ('fullname', models.TextField(blank=True, max_length=256, null=True)),
                ('enname', models.TextField(blank=True, max_length=256, null=True)),
                ('market', models.TextField(blank=True, max_length=18, null=True)),
                ('exchange', models.TextField(blank=True, max_length=18, null=True)),
                ('curr_type', models.TextField(blank=True, max_length=18, null=True)),
                ('list_status', models.TextField(blank=True, max_length=1, null=True)),
                ('list_date', models.TextField(blank=True, max_length=8, null=True)),
                ('delist_date', models.TextField(blank=True, max_length=8, null=True)),
                ('is_hs', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
