# Generated by Django 3.0.4 on 2020-03-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stocks.Stock')),
                ('exchange', models.CharField(blank=True, max_length=18, null=True)),
                ('chairman', models.CharField(blank=True, max_length=36, null=True)),
                ('manager', models.CharField(blank=True, max_length=36, null=True)),
                ('secretary', models.CharField(blank=True, max_length=36, null=True)),
                ('reg_capital', models.FloatField()),
                ('setup_date', models.DateField(blank=True, max_length=8, null=True)),
                ('province', models.CharField(blank=True, max_length=36, null=True)),
                ('city', models.CharField(blank=True, max_length=36, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('office', models.CharField(blank=True, max_length=256, null=True)),
                ('employees', models.IntegerField()),
                ('main_business', models.CharField(blank=True, max_length=256, null=True)),
                ('business_scope', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
